Réseau de neurones
===================

Introduction
------------
Depuis longtemps je voulais me lancer dans les réseaux de neurones, mais je n'en avais pas trouver le temps. C'est maintenant chose faite. Dans cet article je vais vous expliquer mes différentes expériences dans l'apprentissage de cette nouvelle façon de penser la programmation.

Pour des raisons de simplicité et d'un absence de contraintes de performances, j'utiliserai le langage python pour le code métier et la bibliothèque pygame pour la visualisation.

L'ensemble des codes est disponible sur https://github.com/Akanoa/Neural

Perceptron
----------
### Avant-propos
Avant de me lancer dans la création d'un réseau de neurone, j'ai voulu comprendre le fonctionnement d'un neurone. Avant d'aller plus loin, définissons ce qu'est un neurone au sens informatique du terme.

Un neurone est une entité disposant de n entrés et d'une sortie. La sortie est influencée par les entrés, mais aussi par l'ensemble des résultats qui ont prédécés. 


### Enregistrement des différent entraînements
Il est assez rageant de voir qu'a chaque run il faut repartir depuis le dépuis, et que tout l'expérience acquise est perdue. Pour remédier à cela la manière la plus simple est d'enregister l'état du perceptron dans un fichier et de le recharger par la suite. Pour cela, j'ai utilisé le module cPickle qui me permet de sauvegarder un instantanné de l'état d'un objet et le recharger par la suite.
pour cela j'ajoute des actions à ma ligne de commande.
	
* la première "train" 
    